[package]
name = "rust-gtk-habits"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = "0.9"
libadwaita = "0.7"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aes-gcm = "0.10"
argon2 = "0.5"
rand = "0.8"
dirs = "5.0"
